<script setup>
import { inject, computed } from 'vue'
import Convert from '../hooks/Convert.vue'

const { cart, changeCart, deleteCartItem } = inject('cart')
const cartTotal = inject('cartTotal')

const setQty = computed(() => {
  const qtyArray = []
  const maxQty = 20
  for (let i = 1; i <= maxQty; i++) qtyArray.push(i)
  return qtyArray
})
</script>

<template>
  <transition-group name="list-complete" tag="div" class="flex flex-col">
    <div v-for="(cartItem, cartIndex) in cart" :key="cartItem.id" class="list-complete-item">
      <div class="cart__close-button" @click="() => deleteCartItem(cartIndex)"></div>
      <router-link
        :to="`/products/${cartItem.autogeneratedSlug}-p${cartItem.id}`"
        class="flex-initial w-2/12 py-3"
      >
        <img class="w-100 h-100 object-cover" :src="cartItem.smallThumbnailUrl" alt="" />
      </router-link>
      <div class="flex flex-1 flex-col justify-between py-3 text-base xs:text-lg">
        <router-link
          :to="`/products/${cartItem.autogeneratedSlug}-p${cartItem.id}`"
          class="w-10/12"
          >{{ cartItem.name }}</router-link
        >

        <div v-for="option in cartItem.selectedOptions" :key="option.name">
          <span class="mr-1.5">{{ option.name }}</span>
          <span>{{ option.state.find((choice) => choice.active).text }}</span>
        </div>

        <div class="flex justify-between">
          <div>
            <span>Кол-во: </span>
            <select
              class="border-hidden outline-none bg-transparent"
              @change="(e) => changeCart(cartIndex, Number(e.target.value))"
            >
              <option value="" hidden>{{ cartItem.isAdded }}</option>
              <option
                v-for="i in setQty"
                :key="i"
                :value="i"
                :selected="i === cartItem.isAdded ? true : false"
              >
                {{ i }}
              </option>
            </select>
          </div>
          <div>{{ Convert(cartItem.defaultDisplayedPrice * cartItem.isAdded) }}₽</div>
        </div>
      </div>
    </div>
  </transition-group>
  <div v-if="cart.length" class="flex pt-5 justify-between font-bold text-xl">
    <h3>ИТОГО:</h3>
    <div>{{ Convert(cartTotal.totalPrice) }}₽</div>
  </div>
</template>

<style lang="scss" scoped>
.list-complete-item {
  display: flex;
  position: relative;
  column-gap: 1rem;
  border-bottom-width: 2px;
  transition: all 0.5s ease-in-out;
}
.list-complete-enter,
.list-complete-leave-to {
  opacity: 0;
}
.list-complete-leave-active {
  position: absolute;
}

.cart__close-button {
  position: absolute;
  top: 8px;
  right: 0;
  width: 24px;
  height: 24px;

  cursor: pointer;

  &::before,
  &::after {
    content: '';
    position: absolute;
    top: 16px;
    right: -4px;
    width: 22px;
    height: 1px;
    background-color: #a0a0a0;
    transform: rotate(45deg);
  }

  &::after {
    transform: rotate(-45deg);
  }
}

@-moz-document url-prefix() {
  option {
    font-family: Arial, Helvetica, sans-serif;
  }
}
</style>
