<script setup>
defineProps({
  id: Number,
  autogeneratedSlug: String,
  title: String,
  imageUrl: String
})
</script>

<template>
  <article class="categories__item">
    <div class="categories__card w-80 h-80">
      <router-link :to="`/categories/${autogeneratedSlug}-cat${id}`" class="categories__card-img">
        <div class="categories__card-bg" :style="`background-image: url(${imageUrl});`"></div>
        <div class="categories__card-shadow"></div>
      </router-link>
      <router-link
        :to="`/categories/${autogeneratedSlug}-cat${id}`"
        class="categories__card-caption"
      >
        <div>{{ title }}</div>
      </router-link>
    </div>
  </article>
</template>

<style lang="scss" scoped>
@import '../scss/main';

.categories__item {
  border: 1px solid #c5c5c5;
  background-color: aliceblue;
  color: $primary;

  .categories__card {
    position: relative;
    overflow: hidden;
    padding: 5px;
    height: clamp(170px, 16vw, 220px);
    width: clamp(170px, 16vw, 220px);

    @media (max-width: 430px) {
      height: 140px;
      width: 130px;
    }

    .categories__card-img {
      display: inline-block;
      position: absolute;
      width: 100%;
      height: 100%;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;

      .categories__card-bg {
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        // background-image: url(https://d2j6dbq0eux0bg-cdn.ecwid.net/images/58958138/2208510042.jpg);
        // background-image: -webkit-image-set(url(https://d2j6dbq0eux0bg-cdn.ecwid.net/images/58958138/2208510042.jpg) 1x, url(https://d2j6dbq0eux0bg-cdn.ecwid.net/images/58958138/2208510042.jpg) 2x);
        // background-image: -moz-image-set(url(https://d2j6dbq0eux0bg-cdn.ecwid.net/images/58958138/2208510042.jpg) 1x, url(https://d2j6dbq0eux0bg-cdn.ecwid.net/images/58958138/2208510042.jpg) 2x);
        // background-image: -o-image-set(url(https://d2j6dbq0eux0bg-cdn.ecwid.net/images/58958138/2208510042.jpg) 1x, url(https://d2j6dbq0eux0bg-cdn.ecwid.net/images/58958138/2208510042.jpg) 2x);
        // background-image: -ms-image-set(url(https://d2j6dbq0eux0bg-cdn.ecwid.net/images/58958138/2208510042.jpg) 1x, url(https://d2j6dbq0eux0bg-cdn.ecwid.net/images/58958138/2208510042.jpg) 2x);
        background-size: cover;
        background-position: center;
      }

      .categories__card-shadow {
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        background-color: rgba(0, 0, 0, 0.025);
        background-image: linear-gradient(180deg, rgba(255, 255, 255, 0) 50%, #fff 100%);
      }
    }

    .categories__card-caption {
      position: absolute;
      width: 100%;
      right: 0;
      bottom: 0;
      left: 0;
      margin-bottom: 8%;

      div {
        text-align: center;
        font-weight: 700;
        // font-size: 18px;
        @include adaptiv-font(18, 16);
        margin: 0 3px;
      }
    }
  }
}
</style>
