<script setup>
import ShopCat from './ShopCat.vue'
import PreLoad from './PreLoadC.vue'
defineProps({
  categories: Array
})
</script>

<template>
  <section>
    <div v-if="categories.length" class="mx-auto max-w-6xl p-6">
      <h1 class="text-center text-2xl font-bold text-gray-700">Список категорий</h1>

      <div class="flex justify-center flex-wrap gap-5 mt-10">
        <ShopCat
          v-for="cat in categories"
          :key="cat.id"
          :id="cat.id"
          :autogeneratedSlug="cat.autogeneratedSlug"
          :title="cat.nameTranslated.ru"
          :imageUrl="cat.imageUrl"
        />
      </div>
    </div>
    <PreLoad v-else></PreLoad>
  </section>
</template>
