<script setup>
import ShopProd from './ShopProd.vue'
import CartPopUp from './CartPopUp.vue'
import { ref, watch } from 'vue'

const props = defineProps({
  items: Array,
  drawerOpen: Boolean
})

const popUpOpen = ref(false)
const popUpCartItem = ref({})
const emit = defineEmits(['openDrawer', 'clearCart', 'addToCart'])

const openPopUp = (item) => {
  popUpOpen.value = true
  popUpCartItem.value = item
}

const closePopUp = () => {
  popUpOpen.value = false
}

watch(popUpOpen, () => {
  document.body.style.overflow = popUpOpen.value || props.drawerOpen ? 'hidden' : 'visible'
})
</script>

<template>
  <CartPopUp v-if="popUpOpen" @closePopUp="closePopUp" :popUpCartItem="popUpCartItem" />
  <transition-group name="flip-list" tag="div" class="products__wrapper">
    <ShopProd
      v-for="item in items"
      :key="item.id"
      context="shop"
      :id="item.id"
      :autogeneratedSlug="item.autogeneratedSlug"
      :title="item.name"
      :imgUrl_160="item.smallThumbnailUrl"
      :imgUrl_400="item.thumbnailUrl"
      :imgUrl_800="item.hdThumbnailUrl"
      :imgUrl_1500="item.imageUrl"
      :price="item.defaultDisplayedPriceFormatted"
      :options="item.options"
      :openPopUp="() => openPopUp(item)"
      :openDrawer="() => emit('openDrawer', item)"
      :addToCart="() => emit('addToCart', item, 1, [])"
      :clearCart="() => emit('clearCart', item)"
    />
  </transition-group>
</template>

<style lang="scss" scoped>
.flip-list-move {
  transition: transform 0.5s ease-in-out;
}

.products__wrapper {
  display: grid;
  grid-template: repeat(1, 1fr) / repeat(4, 1fr);
  column-gap: clamp(24px, 2.4vw, 38px);
  row-gap: clamp(44px, 3vw, 40px);
  margin-top: clamp(24px, 2vw, 46px);

  @media (max-width: 860px) {
    grid-template: repeat(1, 1fr) / repeat(3, 1fr);
    column-gap: clamp(20px, 1.5vw, 20px);
  }
  @media (max-width: 690px) {
    grid-template: repeat(1, 1fr) / repeat(2, 1fr);
    row-gap: 30px;
  }
  @media (max-width: 480px) {
    grid-template: repeat(1, 1fr) / repeat(1, 1fr);
  }
}
</style>
